### ISSUE TITLE
"Unable to load myo from system directories." - Error

### ISSUE THREAD

**Issue by nok** [nok/myo-processing#1]
There is a curious bug, that Java can't find and load dependent libraries: `Unable to load myo from system directories`.

Here is a workaround for Mac OS users:

Download the official [Mac SDK OS X Beta 5](https://s3.amazonaws.com/thalmicdownloads/mac/myo-sdk-mac-beta5.zip) of Thalmic and copy the file `myo.framework` to `/System/Library/Frameworks/`.

In addition I will push improvements for a better error handling with specific exceptions: [Hub.java#L129](https://github.com/NicholasAStuart/myo-java/blob/master/src/main/java/com/thalmic/myo/Hub.java#L129)

**Comment by struct78** [comment]
If you are still getting the error, you will need to add this directory to your $PATH environment variable:

Open a command line and type:
`touch ~/.bash_profile; open ~/.bash_profile`

Add the following line to .bash_profile:
`export PATH="/System/Library/Frameworks/myo.framework:$PATH"`

Save the file and close it, then type in the command line:
`source ~/.bash_profile`

Close and re-open Processing and your sketch should work.

**Comment by nok** [comment]
Hello @struct78 ,

with the newest update the library [adds](https://github.com/nok/myo-processing/blob/master/src/de/voidplus/myo/Myo.java#L60) the path of the `myo.framework` to the library path automatically.

Happy coding,
Darius
