### ISSUE TITLE
breaks missing in Device.java: public Device vibrate

### ISSUE THREAD

**Issue by SabrinaVerhage** [nok/myo-processing#11]
Myo vibrates short then medium then strong, because breaks are missing from the switch statement :)

**Comment by nok** [comment]
Thank you @SabrinaVerhage,

you are right. I will fix that curious and funny bug. 😄 

Happy coding,
Darius

**Comment by nok** [comment]
https://github.com/nok/myo-processing/blob/4fd7503f89325eb835be7bd11bf8b26ff3d64225/src/de/voidplus/myo/Device.java#L78-L94

Thanks again!
