### ISSUE TITLE
How to use the already classified myoarmband gestures to move mouse cursor?

### ISSUE THREAD

**Issue by Agidew** [nok/myo-processing#13]
Hello
I am having difficulties on How to use the already classified myoarm gestures (FIST,WAVE-IN,WAVE-OUT,FINGER SPREAD and REST) to move the mouse cursor , right, left, up and down using processing ?

**Comment by nok** [comment]
Hello @Agidew,

your question isn't clear for me. Nevertheless you could use the fist gesture to read the accelerometer and gyroscope data, which you can map to a screen position.

Does it help you?

Regards,
Darius
