### ISSUE TITLE
Incompatible with latest firmware/connect version

### ISSUE THREAD

**Issue by moremeyou** [nok/myo-processing#4]
This isn't really an issue. Just wanted to confirm that the library currently doesn't work with Myo Connect 0.8.1 and firmware 1.1.755.

I see that, when in processing, the icon doesn't show the "check mark" as it does when in other connected apps (chrome, etc).

**Comment by nok** [comment]
@moremeyou Thank for the note!

**Comment by struct78** [comment]
I get an error "Unable to connect to Myo Connect. Is Myo Connect running?" with the same version of SDK and firmware. (Myo Connect is definitely running)

**Comment by nok** [comment]
Hello @moremeyou and @struct78 ,

I don't forget that issue. The problem is, that I just have an alpha device, so I can't test the library with the 1.1.755 firmware. I was assuming that the newer version works fine.

Happy coding,
Darius

**Comment by nok** [comment]
Helllo @moremeyou and @struct78,

just now I updated all libraries to the newest version.

Happy coding,
Darius
