### ISSUE TITLE
Cannot change default lock behavior or unlock from Processing

### ISSUE THREAD

**Issue by ando-shah** [nok/myo-processing#5]
The myo.setLockingPolicy(lockingPolicy) API has not been implemented.

This is a problem because in the latest version of Myo SDK (0.8.1), the default lock policy is that it will be locked when either a pose is detected, or timeout (about 3s).

This is clearly a problem since you constantly have to unlock, do a pose, and then it locks itself again.

Thanks!

**Comment by savvasio** [comment]
Any ideas on when/if should we expect this to be implemented? Thanks

**Comment by ando-shah** [comment]
Also, the manual myo.lock() and myo.unlock() functions need to be implemented. 
Cheers,

**Comment by nok** [comment]
Hello @ananda13 and @macromedia ,

I updated the library, now you can control the locking behaviour:

``` java
Myo myo = new Myo(this);

myo.setLockingPolicy(Myo.LockingPolicy.NONE);
myo.setLockingPolicy(Myo.LockingPolicy.STANDARD);

myo.lock();
myo.unlock(Myo.Unlock.HOLD);
myo.unlock(Myo.Unlock.TIMED);
```

Furthermore I added two getter methods to the raw instances:

``` java
Myo myo = new Myo(this);

com.thalmic.myo.Myo rawMyo = myo.getRawMyo();
com.thalmic.myo.Hub rawHub = myo.getRawHub();
```

Please try it out, and happy coding,
Darius

**Comment by savvasio** [comment]
Great news @nok ! Thanks for the good work.
